version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/Source"
  schedule:
    interval: weekly  
  target-branch: main
  commit-message:
    prefix: "Dependency (dependabot/nuget):"
  labels:
  - ":heavy_check_mark: dependencies"
- package-ecosystem: "npm"
  directory: "/Website"
  schedule:
    interval: weekly
  target-branch: main
  commit-message:
    prefix: "Dependency (dependabot/npm):"
  labels:
  - ":heavy_check_mark: dependencies"
