name: Assign label to PRs

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-dependencies-label:
    name: Assign dependencies label
    runs-on: ubuntu-latest
    if: contains(fromJSON('["dependabot[bot]", "transifex-integration[bot]", "imgbot[bot]"]'), github.event.pull_request.user.login)
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: [':heavy_check_mark: dependencies']
            });
